supporting multiple pod_resources files
IBM/network-config-analyzer pull request #100
Opened 2021-11-03 14:21 UTC by shireenf-ibm

#97

2021-11-03 14:54 UTC, shireenf-ibm commented
Hi @zivnevo ,
in this first commit , I've started to add the support of multiple pod list resources in the scheme runner only (cmd line support to be committed later).
I have some questions before finalizing the code:
1. in this commit I suppose that pod list urls/files are seperated by ',' (_treated as python str_ ).
Is this good? we can also write them **as python list** (with '-' before each resource), then I'll need to make this change for all the existing tests.

2. Shouldn't we do the same (supporting multiple files) to the namespace list
for example when I add this :
![image](https://user-images.githubusercontent.com/82180114/140081950-b820e9ae-ab30-4492-8125-2bec9e2cea08.png)
I get the following warning message (because the ns file not added):
![image](https://user-images.githubusercontent.com/82180114/140084131-2ae659f1-927b-45c7-87b8-f4d22e13da74.png)

2021-11-04 10:10 UTC, zivnevo commented
1. I prefer a yaml list with '-'. There is no need to change existing tests. Just check in the code for the type of the value, convert strings to a list of length 1, then iterate the list.
2. Good idea. Let's do the same for namespaceList to be consistent.
3. Ignore this warning. It's expected.

2021-11-11 12:27 UTC, zivnevo requested changes
Looks good. Just a few minor fixes

2021-11-11 12:27 UTC, zivnevo commented on network-config-analyzer/SchemeRunner.py
> +        return resources_list
```suggestion
        input_file_list = []
        for resource in resources_list:
            input_file_list.append(self._get_input_file(resource))
        return input_file_list
```
Better not override the list given as input

2021-11-11 12:27 UTC, zivnevo commented on network-config-analyzer/SchemeRunner.py
> +    def _handle_resorces_list(self, resources_list):
fix typo in function name

2021-11-11 12:27 UTC, zivnevo commented on network-config-analyzer/PeerContainer.py
> +           self.load_peer_from_k8s_live_cluster()
```suggestion
        if not peer_resources_list:
            self.load_peer_from_k8s_live_cluster()
```
Fix indentation

2021-11-11 12:27 UTC, zivnevo commented on network-config-analyzer/PeerContainer.py
> +
remove redundant line
```suggestion
```

2021-11-11 13:32 UTC, zivnevo approved these changes
ok to merge

2021-11-11 16:03 UTC, merged