Issue 358 restyle dot graph
IBM/network-config-analyzer pull request #414
Opened 2023-01-25 15:15 UTC by haim-kermany

restyling the dot graph:
1. subgroup nodes into namespaces
2. represents cliques as nodes - to reduce number of edges
3. sorting edged names
4. restyling shapes and colors

updated expected results accordingly

2023-02-15 10:05 UTC, zivnevo requested changes
Great work.
Some comments (mostly minor changes).

2023-02-16 08:29 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
Currently, I put all the IPblocks under a subgraph calles 'external' (according to Ed Snible suggestion) but it is not related to this code.
We do have nodes not inside a subgraph - the clq nodes. for these nodes, the subgraph is an empty string.
Do you think we should to move the ipblocks outside the subgraph?

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/ConnectivityGraph.py
> +        not_directed_edges = set([edge for edge in directed_edges if (edge[1], edge[0]) in directed_edges])
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/ConnectivityGraph.py
> +        not_directed_edges = set([edge for edge in not_directed_edges if edge[1] < edge[0]])
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/ConnectivityGraph.py
> +            clq_namespaces = sorted(set([peer[1] for peer in clique]))
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/ConnectivityGraph.py
> +                    not_directed_edges |= set([(namespace_clique_node, node) for node in clq_namespace_peers])
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/ConnectivityGraph.py
> +    def _creates_cliqued_graph(self, directed_edges):
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +        if subgraph not in self.subgraphs.keys():
done

2023-02-16 08:30 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +        first_tokens = set([t[0] for t in labels_tokens.values()])
done

2023-02-16 08:31 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            token_labels = [label for label in labels_tokens.keys() if labels_tokens[label][0] == first_token]
done

2023-02-16 08:31 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            self.is_dir = is_dir
done

2023-02-16 10:33 UTC, zivnevo commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
I don't think grouping all IP-Blocks in a box makes much sense. It's not as if Google's IPs have something to do with Amazon's IPs. @adisos , what do you think?

2023-02-16 10:42 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +        labels_tokens = {}
correct, the sort in not in the right place - fixed and documented

2023-02-16 11:20 UTC, adisos commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
Is it related to grouping if they have the exact same ingress/egress connections?

2023-02-16 11:56 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
no, it is related to that all nodes of the same namespace are in the same subgraph.

2023-02-16 11:59 UTC, adisos commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
so I think I agree with @zivnevo , and would not group all IP blocks

2023-02-16 13:37 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            self.node_type = node_type
done

2023-02-16 13:38 UTC, haim-kermany commented on nca/FWRules/DotGraph.py
> +            self.subgraphs[subgraph] = self.Subgraph(subgraph)
so moved the ip-blocks from subgraph - done

2023-02-16 13:50 UTC, zivnevo approved these changes

2023-02-16 14:12 UTC, merged