remove trivial conns from workload to itself in txt-no-fw-rules format
IBM/network-config-analyzer pull request #510
Opened 2023-05-29 08:31 UTC by shireenf-ibm

2023-06-05 10:07 UTC, adisos requested changes
hi @shireenf-ibm , looks good. 
Please create an issue to explain this change. and also update documentation for this output format.

2023-06-05 11:14 UTC, adisos requested changes

2023-06-05 11:53 UTC, shireenf-ibm commented on nca/FWRules/ConnectivityGraph.py
> +        :return: a string of the original peers connectivity graph content, excluding connections between workload to itself
worth thinking about it -
-> on the one hand, I am not sure this keeps the correctness of the semantic diff result
but on the other hand,
how common is the cases of changes to self-loop connections for different configurations?!
(when having two network-policy sets: Is it common to change connections between workload to itself ?
or is it common to add/remove replicas of persistent peers when having two configuration topology?)

2023-06-05 11:56 UTC, adisos commented on nca/FWRules/ConnectivityGraph.py
> +        :return: a string of the original peers connectivity graph content, excluding connections between workload to itself
I think that for correctness considerations, we should consider such `connectivity-diff` in the output as well.

2023-06-05 12:51 UTC, adisos commented on nca/FWRules/ConnectivityGraph.py
> +                        continue
can you also add a test for semantic-diff, for which a connection between workload to itself is in the output of the connectivity diff in this format?

2023-06-06 04:33 UTC, adisos commented on nca/FWRules/ConnectivityGraph.py
> +                        continue
ok, great! how did it not fail in one of the previous commits on which such connections were removed from the output? 
Is that example tested on txt_no_fw_rules format?  if not, let's add this format to that test as well.

2023-06-06 04:51 UTC, adisos commented on nca/FWRules/ConnectivityGraph.py
> +                        continue
now I noticed you've added this format to that test.. thanks!

2023-06-06 04:52 UTC, adisos approved these changes

2023-06-06 06:20 UTC, merged